#!/usr/bin/env python3
"""
CSSファイルにコメントとセクション分けを追加
表示に影響しないコメントのみを追加
"""

def add_css_documentation(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # ファイルの先頭にドキュメントヘッダーを追加
    header = """/* =================================================================
   ALC Study Unlimited - Main Stylesheet
   Generated by Webflow and optimized for maintainability
   
   Table of Contents:
   1. CSS Custom Properties (Variables)
   2. Base Styles and Resets
   3. Typography
   4. Layout Components
   5. Form Elements
   6. Interactive Elements
   7. Utility Classes
   8. Media Queries
   9. Webflow-specific Grid Layouts
   ================================================================= */

"""
    
    # :rootセクションの前にコメントを追加
    content = content.replace(':root {', 
"""/* =================================================================
   1. CSS CUSTOM PROPERTIES (VARIABLES)
   ----------------------------------------------------------------
   These variables control the design system of the website.
   They are generated by Webflow but can be overridden if needed.
   Use the shorter aliases defined in variable_aliases.css for
   better readability when making changes.
   ================================================================= */

:root {""")
    
    # メディアクエリセクションの前にコメント追加
    content = content.replace('@media screen and (max-width: 991px)',
"""/* =================================================================
   8. MEDIA QUERIES - Tablet and below (max-width: 991px)
   ================================================================= */

@media screen and (max-width: 991px)""")
    
    content = content.replace('@media screen and (max-width: 767px)',
"""/* =================================================================
   MEDIA QUERIES - Mobile Landscape (max-width: 767px)
   ================================================================= */

@media screen and (max-width: 767px)""")
    
    content = content.replace('@media screen and (max-width: 479px)',
"""/* =================================================================
   MEDIA QUERIES - Mobile Portrait (max-width: 479px)
   ================================================================= */

@media screen and (max-width: 479px)""")
    
    # 出力ファイルに保存
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header + content)
    
    print(f"Documentation added to: {output_file}")

# 実行
add_css_documentation(
    'css_backup/staged/alc-study-unlimited.webflow-with-comments.css',
    'css_backup/staged/alc-study-unlimited.webflow-documented.css'
)
